name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Node.js app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy app to VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e
            cd ~/chat_websocket || git clone https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git ~/chat_websocket && cd ~/chat_websocket
            git pull origin main
            npm install
            npm run build
            npm run migration:run
            pm2 restart chat-api || pm2 start 'npm run start' --name chat-api
          EOF
